# https://gandalab.com/como-crear-configurar-utilizar-mysql-en-un-contenedor-de-docker/:
# Use root/mysql as user/password credentials

version: '3.8'

services:

  db:
    container_name: mysql
    image: mysql:8.0
    command:
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
    ports:
      - "3306:3306"
    networks:
      - db

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8089:8080
    networks:
      - db

networks:
  db:
    driver: bridge